name: Feature branch checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  #First job
  setup:
    name: Setup code and environment needed for linting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Node modules
        run: yarn install --immutable

      - name: Linting
        run: yarn lint
